apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messageq
  name: messageq
  namespace: coffee-shop  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messageq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: messageq
    spec:
      containers:
      - image: ghcr.io/itamar81/micro-services-arch/messageq:1.10
        name: messageq
        env:
        - name: RABBIT_PASSWORD
          value: "vkbHAhGx0KPiONXR"
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
         
        resources: {}
      restartPolicy: Always